feat: mobile main hud
decentraland/godot-explorer pull request #169
Opened 2024-01-16 14:16 UTC by kuruk-mm

2024-01-18 14:29 UTC, leanmendoza requested changes
Some minor reviews
Regarding the tests:
- Download the `snapshots.zip` from the CI summary and get the right snapshots to replace in `repo/tests/snapshots`
- Before replacing text-shape's snapshots, see what and why they're changing

2024-01-18 14:29 UTC, leanmendoza commented on .github/workflows/android-build.yml
> +  release:
we're not using github release pipeline

2024-01-18 14:29 UTC, leanmendoza commented on godot/.godot/global_script_class_cache.cfg
> +"path": "res://src/ui/components/safe_margin_container/SafeMarginContainer.gd"
```suggestion
"path": "res://src/ui/components/safe_margin_container/safe_margin_container.gd"
```

2024-01-18 14:29 UTC, leanmendoza commented on godot/src/logic/player/player.gd
> +	elif Input.is_action_pressed("ia_jump"):
🙌

2024-01-18 14:29 UTC, leanmendoza commented on godot/src/main.gd
> +		#resolution_manager.change_window_size(
dead code
this is still in the settings

2024-01-18 14:29 UTC, leanmendoza commented on godot/src/mobile/joystick/virtual_joystick.gd
> +func custom_input(event: InputEvent) -> void:
can you detail how this works?

2024-01-18 14:29 UTC, leanmendoza commented on godot/src/ui/components/safe_margin_container/SafeMarginContainer.gd
change filename

2024-01-18 18:38 UTC, kuruk-mm commented on .github/workflows/android-build.yml
> +  release:
it's temp for copy paste

2024-01-19 11:38 UTC, leanmendoza approved these changes
Nice work, looks good to me 😄 
Just fix tests before merging

2024-01-19 18:49 UTC, merged